name: Test Deno Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        deno-version: [1.37.2]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v4
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      # - name: Format Check
      #   run: deno fmt --check
      - name: Lint
        run: deno lint
      - name: Asset Check
        run: |
          deno task build_assets
          git diff --exit-code src/assets.json
      - name: Test
        run: deno task test
