name: Test Deno Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.35.2]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v4
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Format Check
        run: deno fmt --check
      - name: Lint
        run: deno lint
      - name: Test
        run: deno task test
