name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '42 19 * * *'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ vars.DENO_VERSION }}
      - name: Update dependencies
        run: |
          deno run -A https://deno.land/x/udd/main.ts src/deps/*.ts src/deps/std/*.ts
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: pr
        with:
          token: ${{ secrets.PAT_FOR_DECOR_UDD }}
          commit-message: 'Update dependencies'
          title: Update dependencies
          body: >
            Dependencies updated by [udd](https://github.com/hayd/deno-udd).
          branch: deno-dependency-updates
          author: GitHub <noreply@github.com>
          delete-branch: true
